stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"

criar_images:
   stage: build
   image: docker:24.0.5
   services:
    - docker:24.0.5-dind
   before_script:
    - docker login -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASS} docker.io
   script:
    - docker build --no-cache -t helterpitanga/appmicro1:6.0 app/.
    - docker push helterpitanga/appmicro1:6.0

deploy_EKS:
  stage: deploy
  image: helterpitanga/eksconfigure:1.0
  needs:
    - criar_images
  script: 
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - aws eks --region us-east-1 update-kubeconfig --name ekscluster
    - kubectl apply -f appdeployments/appdeployment.yml
    - kubectl apply -f appdeployments/applb.yml