stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  VERSION: "4.0"

criar_images:
   stage: build
   image: docker:24.0.5
   services:
    - docker:24.0.5-dind
   before_script:
    - docker login -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASS} docker.io
   script:
    - docker build --no-cache -t helterpitanga/appmicro2:$VERSION app2/.
    - docker push helterpitanga/appmicro2:$VERSION

deploy_EKS:
  stage: deploy
  image: helterpitanga/eksconfigure:1.0
  needs:
    - criar_images
  script: 
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - aws eks --region us-east-1 update-kubeconfig --name ekscluster
    - kubectl apply -f app2deployments/appdeployment.yml
    - kubectl apply -f app2deployments/mysql.yml
    - kubectl apply -f app2deployments/applb.yml