stages:
  - "ConnectEKS"

connect_EKS:
  stage: "ConnectEKS"
  image: helterpitanga/eksconfigure:1.0
  script: 
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - aws eks --region us-east-1 update-kubeconfig --name ekscluster
  after_script:
    - kubectl get nodes