stages:
  - ConnectEKS
  - build
  - deploy

variables:
  VERSION: "1.0"
  DOCKER_TLS_CERTDIR: "/certs"

connect_EKS:
  stage: "ConnectEKS"
  image: helterpitanga/eksconfigure:1.0
  script: 
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - aws eks --region us-east-1 update-kubeconfig --name ekscluster

criar_images:
   stage: build
   needs:
     - connect_EKS
   image: docker:24.0.5
   services:
    - docker:24.0.5-dind
   before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin docker.io
   script:
    - docker build -t helterpitanga/appmicro1:$VERSION app/.
    - docker push helterpitanga/appmicro1:$VERSION
